[versions]
agp = "8.13.2"
annotation = "1.9.1"
annotationExperimental = "1.5.1"
appcompat = "1.7.1"
commonsIo = "2.21.0"
constraintlayout = "2.2.1"
coordinatorlayout = "1.3.0"
core = "1.17.0"
desugar_jdk_libs = "2.1.5"
drawerlayout = "1.2.0"
espressoCore = "3.7.0"
fragmentKtx = "1.8.9"
guava = "33.5.0-jre"
junit = "4.13.2"

junitVersion = "1.3.0"
lifecycleLivedataCoreKtx = "2.10.0"
listenablefuture = "9999.0-empty-to-avoid-conflict-with-guava"
loader = "1.1.0"
markwonVersion = "4.6.2"
material = "1.14.0-alpha09"

preference = "1.2.1"
realtimeblurview = "f54dc3c34d"
recyclerview = "1.4.0"
restrictionbypass = "2.2"
robolectric = "4.16.1"
savedstate = "1.4.0"
transition = "1.7.0"
vectordrawableAnimated = "1.2.0"
versionedparcelable = "1.2.1"
viewpager = "1.1.0"
viewpager2 = "1.1.0"
window = "1.5.1"

[libraries]
annotation-experimental = { module = "androidx.annotation:annotation-experimental", version.ref = "annotationExperimental" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
core = { module = "androidx.core:core", version.ref = "core" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
ext-strikethrough = { module = "io.noties.markwon:ext-strikethrough", version.ref = "markwonVersion" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lifecycle-livedata-core-ktx = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "lifecycleLivedataCoreKtx" }
linkify = { module = "io.noties.markwon:linkify", version.ref = "markwonVersion" }
listenablefuture = { module = "com.google.guava:listenablefuture", version.ref = "listenablefuture" }
loader = { module = "androidx.loader:loader", version.ref = "loader" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "markwonVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
realtimeblurview = { module = "com.github.mmin18:realtimeblurview", version.ref = "realtimeblurview" }
recycler = { module = "io.noties.markwon:recycler", version.ref = "markwonVersion" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
restrictionbypass = { module = "com.github.ChickenHook:RestrictionBypass", version.ref = "restrictionbypass" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
savedstate = { module = "androidx.savedstate:savedstate", version.ref = "savedstate" }
transition = { module = "androidx.transition:transition", version.ref = "transition" }
vectordrawable-animated = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "vectordrawableAnimated" }
versionedparcelable = { module = "androidx.versionedparcelable:versionedparcelable", version.ref = "versionedparcelable" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
viewpager = { module = "androidx.viewpager:viewpager", version.ref = "viewpager" }
window = { module = "androidx.window:window", version.ref = "window" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
